kind: Service
apiVersion: v1

metadata:
  name: api-hello-svc
  namespace: 00-testing

spec:
  type: ClusterIP
  selector:
    app: api-hello
  ports:
  - protocol: TCP
    port: 80          # Port of the Service
    targetPort: 8080  # Port of the Pod
