---
- name: Run 'shutdown now', good night babies !!!!
  hosts: cool_servers
  become: yes
  become_user: root
  tasks:
    - name: Run 'shutdown now' in Fedora's Distribution
      command: shutdown +1
      when: ansible_distribution == 'Fedora'
    
    - name: Run 'shutdown now' in Ubuntu's Distribution
      command: shutdown +1
      when: ansible_distribution == 'Ubuntu'