pipeline {
    agent any

    stages {
        stage('docker build') {
            steps {
                script {
                    sh "docker build -f homer_simpson_pipeline/Dockerfile -t caosbinario/homer_page:1.0.0-${BUILD_ID} homer_simpson"
                }
            }
        }
    }
}