kind: Service
apiVersion: v1

metadata:
  name: api-hello-one-svc
  namespace: 00-testing # <-- Remember the namespace binding.
  labels:
    app: api-hello-one

spec:
  type: ClusterIP
  selector:
    app: api-hello-one
  ports:
  - protocol: TCP
    port: 80          # Port of the Service
    targetPort: 8080  # Port of the Pod

---

kind: Service
apiVersion: v1

metadata:
  name: api-hello-two-svc
  namespace: 00-testing # <-- Remember the namespace binding.
  labels:
    app: api-hello-two

spec:
  type: ClusterIP
  selector:
    app: api-hello-two
  ports:
  - protocol: TCP
    port: 80          # Port of the Service
    targetPort: 8080  # Port of the Pod
